### ISSUE TITLE
NativeDMXController init error 

### ISSUE THREAD

**Issue by denischiron** [benkuper/AIR-NativeExtensions#6]
Hi,

I've tried to build a basic example with NativeDMXController but i could not compile it.

As others, I've got the message :
 Error #3500: The extension context does not have a method with the name init.

I read your previous messages about depencies, but I'm not sure how to fix it.

Could you tell me if I can solve this issue without recompiling the extension ?
Is a DLL is missing in the ANE, or on my system ? FTD2XX.dll ?

Thanks by advance,
Denis

- .Net 4.5 & 4.6 are installed on my PC
- the message appears in Flash IDE and Flash Develop.

**Comment by denischiron** [comment]
PS : An .exe published with Flash asks for : msvcp110d.dll (once FTD2XX.dll is provided).
Same thing for the NativeSerial.ane extension.

**Comment by benkuper** [comment]
Hello,
you're right there are 3 dependencies , one to ftd2xx and 2 two the microsoft runtimes : 
you can fin them there : http://fr.dll-files.com/msvcp110d.dll.html and http://fr.dll-files.com/msvcr110d.dll.html (be sure to choose the 32-bit version)
And a reminder for those who also needs ft2dxx : http://www.ftdichip.com/Drivers/VCP.htm

In order to make them work with flashDevelop, you have to copy those 3 files in the SDK folder/bin, next to adl.exe (or add to the PATH environment variable the path to a folder containing those dll)

When packaging the app (with FlashDevelop also), those dll must be copied in the /bin folder of your project, next to the swf

I'm not sure for FlashIDE but it should be the same.

Cheers

**Comment by denischiron** [comment]
Thanks for your comment.

I've just discovered that the dll msvcp110.dll was corrupted on my computer.
The extension loads without the "init" message now.
I will let you know when I'll test with the ENTEC Usb/dmx device.

Denis

**Comment by datee** [comment]
This is driving me crazy... I have one computer where this works fine, but i cannot get it working on any others... I only get the Error #3500: The extension context does not have a method with the name init. no matter what.... I have put the same dependency dll's in the same folder as the exe.. and even in windows system 32.. ..Dont work... Any idea as to what is going on? (windows 10)

**Comment by denischiron** [comment]
Hi,

Have you built and tested an .exe on your PC ?

As far as I remember, launching the exe is the best way to get the Alert 
from the system, asking for missing DLLs.
If Windows asks for a DLL, then you can had the missing DLL near the 
.exe and launch the program again.

It solved my problem on my PC and on my client PC also : his PC asked 
for different DLLs than mine.

Check out your DLL too, one of DLL was corrupted (i've found it on 
Internet at the beginning of my tests, before installing Visual Studio).
And everything worked after replacing it.

Hope it helps.
Denis


> This is driving me crazy... I have one computer where this works fine, 
> but i cannot get it working on any others... I only get the Error 
> #3500: The extension context does not have a method with the name 
> init. no matter what.... I have put the same dependency dll's in the 
> same folder as the exe.. and even in windows system 32.. ..Dont 
> work... Any idea as to what is going on? (windows 10)

**Comment by benkuper** [comment]
Hello, are you using flashdevelop ?
You have to put the dependendcy dlls aside the adl.exe file in the adobe
SDK bin folder.
It's been a long time since I last used this extension. I don't have much
time now but I'll try to test that

Le lun. 21 nov. 2016 08:51, Denis Chiron <notifications@github.com> a
écrit :
